### ISSUE TITLE
rollup: multiple workspaces

### ISSUE THREAD

**Issue by tunnckoCore** [rx-ts/pkgr#36]
For monorepo setups, it should work for these scenarios too

```
@tunnckocore/
- kokoko/ # (named: `@tunnckocore/kokoko`)
--- src/
@hela/
- dev/ # (named: `@hela/dev`)
--- src/
configs
- eslint-config (named: `@tunnckocore/eslint-config`)
- babel-preset (named: `@tunnckocore/babel-preset`)
- ... etc
packages/
- foo/
--- src/
- bar/
--- src/
```

lerna config

```json
  "packages": [
    "configs/*",
    "packages/*",
    "@tunnckocore/*",
    "@hela/*"
  ],
```

Or even if it doesn't support that... it still won't support through the `--monorepo` flag the following

```json
  "packages": [
    "packages/@tunnckocore/*",
    "packages/@hela/*",
    "packages/configs/*",
    "packages/web/*",
    "packages/*",
  ],
```

To the rescue can com the [@tunnckocore/utils](https://ghub.now.sh/@tunnckocore/utils) package. Check it out.

The thing is that I want to have a clear and visible separation between what's what, what's scoped and what's not.

**Comment by JounQin** [comment]
Pretty cool idea, it will consider implementing it in a few days.

**Comment by JounQin** [comment]
It seems I've implement it at https://github.com/1stG/configs/blob/master/packages/eslint-config/_util.js#L8-L35 , will extract it into `@pkgr/utils` instead for sharing same logic.

**Comment by tunnckoCore** [comment]
Yea, I remember that. But definitely waste of using `glob`, `isGlob` and etc. Use just `path.dirname` - 99% of the cases it's `packages/*` so path.dirname will get the correct thing, then just check if it exists and continue with the others. ;]

**Comment by tunnckoCore** [comment]
Or just found the `get-workspaces` package which works with all major Workspaces solutions, except Lerna nad Pnpm :D

**Comment by JounQin** [comment]
I'm using `tiny-glob` instead of `glob` there which is much lighter. And it has been used in `eslint-import-resolver-typescript` which is very common dev dependence, so I prefer keep `tiny-glob` as is, and also for robustness.

I personally will migrate to `pnpm` in near feature also, so `get-workspaces` would be cool if it supports them out of box.

Very appreciate for your reviewing.

**Comment by tunnckoCore** [comment]
> I personally will migrate to pnpm in near feature also

Same here, just testing last few days and, except some ESLint loading problems (needed to copy paste all the deps from the config, to the monorepo root) it - works.

> I'm using tiny-glob instead of glob there which is much lighter

Sure, I know. But it gives you nothing more than just `fs.readdir(Sync)`.
