### ISSUE TITLE
rollup: pass output.name only if format is umd

### ISSUE THREAD

**Issue by tunnckoCore** [rx-ts/pkgr#37]
The `name: pkgGlobals[name]`. It's not an error and Rollup doesn't fail for now, but still. It's unnecessary.

**Comment by JounQin** [comment]
Thx for advice, but why should care about it if they emit same outputs anyway?

**Comment by tunnckoCore** [comment]
It's not clean, it may be misleading to beginners looking at the code, it's not safe against future rollup/API (breaking) changes - not future-proof.

:P It's style, self preference. But a good habit. :)

**Comment by JounQin** [comment]
This package is strict TypeScript based, and if rollup API changed for this tiny option, then a big BREAKING CHANGE would be possible, so then we will have to refactor the code anyway.

I don't want to add redundant logic if it won't change anything.
