### ISSUE TITLE
rollup: add `external: (id: string) => boolean` or allow externals to be function

### ISSUE THREAD

**Issue by tunnckoCore** [rx-ts/pkgr#38]
What I'm doning in one place is 

```js
const externals = Object.keys(pkg.dependencies || {})
  .concat(builtins)
  .filter(Boolean);

const external = (id) => externals.find((x) => {
  // resolves the `foo/bar` scenario which you are doing with .includes('/')
  return id.startsWith(x)
});

// pass `external` to the RollupOptions.
```

Not to mention that globbing would be cool too. Using `nanomatch` or `micromatch`. (btw, same apply for the `exclude`)

Lets make this smart and robust one :) By the way, monorepo support isn't that big of a deal, because we have `jest-runner-rollup` which handles this brilliantly (not to mention the builtin incremental smart cache ) and can accept generated from this config.

**Comment by JounQin** [comment]
https://github.com/rx-ts/pkgr/blob/master/packages/rollup/src/config.ts#L283-L284

It does use functional external option, is there any case it would work unexpected?

**Comment by tunnckoCore** [comment]
It's not about if there is cases that it would work unexpected ;p 

The thing is about to allow the user to pass own function, he may want another check. As I said, for example using `micromatch` or regex or whatever. ;]

Oh, i forgot to add the thing in the snippet above ;d

Something like that:

```js
const externals = Object.keys(pkg.dependencies || {})
  .concat(builtins)
  .filter(Boolean);

const defaultExternalFn = (id) => externals.find((x) => {
  // resolves the `foo/bar` scenario which you are doing with .includes('/')
  return id.startsWith(x)
});

// passed to `RollupOptions.external`
const external = (id) => typeof opts.external === 'function'
  ? opts.external(id, externals)
  : defaultExternalFn(id)
```

**Comment by JounQin** [comment]
Understand. But this package is a cli tool at first place so function seems not suitable here. I prefer glob for now and am considering integrate with `cosmiconfig` so that the cli command could be shorter and function option would be possible then.

**Comment by JounQin** [comment]
Besides, `id.startsWith(x)` is not correct because `foo` should not cover `foo-bar`.

**Comment by tunnckoCore** [comment]
> is not correct because foo should not cover foo-bar.

Ah, good catch. :laughing: 

> But this package is a cli tool at first place so function seems not suitable here

It still is possible to just use/import/require the config file ;)

**Comment by tunnckoCore** [comment]
One more cool package: https://github.com/stevenbenisek/rollup-plugin-auto-external

**Comment by JounQin** [comment]
I added supports of globs, regexps and function for `externals` option. And I just realized `regexp` support should be enough rather than `glob`. 🤣

**Comment by tunnckoCore** [comment]
better

```js
const collectedExternals = Object.keys(dependencies || {}).concat(
  Object.keys(peerDependencies || {}),
  node ? deps.concat(builtinModules) : [],
)

// later
external: (id) => {
  if (typeof externals === 'function') {
    return externals(id, collectedExternals)
  }

  const extern = Array.isArray(externals) ? externals : collectedExternals

  return extern.some(val => {
    /* the same as in the commit */
  })
}
```

**Comment by tunnckoCore** [comment]
Btw, this way, you also give one cool feature. Users can define what's external and what's not by just putting it in the package `dependencies`. Otherwise, they shouldn't put them there because we bundle external dependencies by default.

**Comment by JounQin** [comment]
`external` packages should be `peerDependencies` in my opinion. I got this idea from upcoming [`parcel@2`](https://github.com/parcel-bundler/parcel/issues/3305#issuecomment-542772700).

And `dependencies` is external by default for `node` packages: https://github.com/rx-ts/pkgr/blob/master/packages/rollup/src/config.ts#L275.

**Comment by tunnckoCore** [comment]
Oooh, yea, I missed that `const deps` line :D
