### ISSUE TITLE
rollup: allow to force using Babel for TS inputs

### ISSUE THREAD

**Issue by tunnckoCore** [rx-ts/pkgr#87]
Hi and Happy New Year!

I was looking the source codes around again, I thought that it would be good to allow to process TypeScript source/input with Babel. And one more thing: allow disabling the default `babel/preset-env` (so, it will be only `babel()` and so will read from a config) cuz I want to use the new `preset-modules` plus more optimizing plugins.

**Comment by JounQin** [comment]
Great idea! And PR welcome!

**Comment by tunnckoCore** [comment]
Okay, I'll look into it.
